Repository UMAprotocol/protocol, pull requests merged in 2020-12, with the labels that each got.

#2262 improve(perpetual) move proposal time bounds into config store
  packages/core/contracts/financial-templates/common/FundingRateApplier.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/ConfigStore.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/ConfigStoreInterface.sol
  packages/core/test/financial-templates/common/FundingRateApplier.js
  packages/core/test/financial-templates/perpetual-multiparty/ConfigStore.js
  packages/core/test/financial-templates/perpetual-multiparty/Perpetual.js
  packages/core/test/financial-templates/perpetual-multiparty/PerpetualCreator.js
  packages/core/test/financial-templates/perpetual-multiparty/PerpetualLiquidatable.js
  packages/core/test/financial-templates/perpetual-multiparty/PerpetualPositionManager.js
Labels: funding-rate-applier

#2278 feat(fee-payer): Add gulp method to distribute excess collateral to all sponsors
  packages/core/contracts/financial-templates/common/FeePayer.sol
  packages/core/contracts/financial-templates/expiring-multiparty/Liquidatable.sol
  packages/core/contracts/financial-templates/expiring-multiparty/PricelessPositionManager.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualPositionManager.sol
  packages/core/test/financial-templates/expiring-multiparty/PricelessPositionManager.js
  packages/core/test/financial-templates/perpetual-multiparty/PerpetualPositionManager.js
Labels: position-manager

#2280 fix(funding-rate-applier): reset proposal time to 0 if proposal doesn't exist
  packages/core/contracts/financial-templates/common/FundingRateApplier.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLiquidatable.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualPositionManager.sol
  packages/core/test/financial-templates/common/FundingRateApplier.js
Labels: bug, funding-rate-applier

#2308 fix(dec-2020-audit): [L08] Misleading comments
  packages/core/contracts/common/implementation/FixedPoint.sol
  packages/core/contracts/financial-templates/common/FundingRateApplier.sol
  packages/core/contracts/financial-templates/common/financial-product-libraries/FinancialProductLibrary.sol
  packages/core/contracts/financial-templates/common/financial-product-libraries/PreExpirationIdentifierTransformationFinancialProductLibrary.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/ConfigStore.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualPositionManager.sol
  packages/core/contracts/oracle/implementation/OptimisticOracle.sol
  packages/core/contracts/oracle/interfaces/OptimisticOracleInterface.sol
Labels: dec-2020-audit

#2303 fix(dec-2020-audit): [L05] Event missing emit keyword
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualCreator.sol
Labels: dec-2020-audit

#2314 fix(dec-20-audit): [L11] Propose or Dispute a price from the zero address
  packages/core/contracts/oracle/implementation/OptimisticOracle.sol
  packages/core/test/oracle/OptimisticOracle.js
Labels: dec-2020-audit

#2309 fix(dec-20-audit): [L02] Complex Repay Function
  packages/core/contracts/financial-templates/expiring-multiparty/PricelessPositionManager.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualPositionManager.sol
  packages/core/test/financial-templates/expiring-multiparty/PricelessPositionManager.js
  packages/core/test/financial-templates/perpetual-multiparty/PerpetualPositionManager.js
Labels: dec-2020-audit

#2304 fix(dec-20-audit): [L07] Incorrect error message
  packages/core/contracts/financial-templates/expiring-multiparty/Liquidatable.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLiquidatable.sol
Labels: dec-2020-audit

#2312 fix(dec-2020-audit): [N08] Typographical errors
  packages/core/contracts/financial-templates/common/FundingRateApplier.sol
  packages/core/contracts/financial-templates/common/financial-product-libraries/PreExpirationIdentifierTransformationFinancialProductLibrary.sol
  packages/core/contracts/financial-templates/common/financial-product-libraries/StructureNoteFinancialProductLibrary.sol
  packages/core/contracts/financial-templates/expiring-multiparty/PricelessPositionManager.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/ConfigStore.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualCreator.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLiquidatable.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualPositionManager.sol
  packages/core/contracts/oracle/implementation/OptimisticOracle.sol
  packages/core/contracts/oracle/interfaces/OptimisticOracleInterface.sol
Labels: dec-2020-audit

#2315 fix(dec-2020-audit): [N09] Unnecessary imports
  packages/core/contracts/financial-templates/common/FundingRateApplier.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualPositionManager.sol
Labels: dec-2020-audit

#2317 fix(dec-2020-audit): [N03] Incorrect filename
  packages/core/contracts/financial-templates/common/financial-product-libraries/StructuredNoteFinancialProductLibrary.sol
Labels: dec-2020-audit

#2316 fix(dec-2020-audit): [N10] Unnecessary type cast
  packages/core/contracts/financial-templates/expiring-multiparty/ExpiringMultiPartyCreator.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualCreator.sol
Labels: dec-2020-audit

#2305 fix(dec-2020-audit): [L09] Missing NatSpec comments
  packages/core/contracts/financial-templates/perpetual-multiparty/ConfigStore.sol
  packages/core/contracts/oracle/implementation/Voting.sol
  packages/core/contracts/oracle/interfaces/OracleAncillaryInterface.sol
Labels: dec-2020-audit

#2319 fix(dec-20-audit): [L06] Inconsistent hasPrice determination
  packages/core/contracts/oracle/implementation/OptimisticOracle.sol
  packages/core/test/oracle/OptimisticOracle.js
Labels: dec-2020-audit

#2310 fix(dec-20-audit): [L04] Emergency shutdown defined at the wrong level
  packages/core/contracts/financial-templates/common/EmergencyShutdownable.sol
  packages/core/contracts/financial-templates/common/FundingRateApplier.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualPositionManager.sol
Labels: dec-2020-audit

#2311 fix(dec-20-audit): [M01] Lack of event emission after sensitive actions
  packages/core/contracts/financial-templates/common/FundingRateApplier.sol
  packages/core/test/financial-templates/common/FundingRateApplier.js
Labels: dec-2020-audit

#2306 fix(dec-2020-audit): [L10] Functions not failing early
  packages/core/contracts/financial-templates/expiring-multiparty/PricelessPositionManager.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualCreator.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualPositionManager.sol
Labels: dec-2020-audit

#2313 fix(dec-20-audit): [L03] Current config not update
  packages/core/contracts/financial-templates/common/FundingRateApplier.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/ConfigStore.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/ConfigStoreInterface.sol
  packages/core/test/financial-templates/perpetual-multiparty/ConfigStore.js
Labels: dec-2020-audit

#2328 fix(dec-20-audit): [N01] Add notes about Approximate compounding
  packages/core/contracts/financial-templates/common/FeePayer.sol
  packages/core/contracts/financial-templates/common/FundingRateApplier.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLiquidatable.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualPositionManager.sol
Labels: dec-2020-audit

#2318 fix(dec-2020-audit): [M02] Functions with unexpected side-effects
  packages/core/contracts/financial-templates/common/FundingRateApplier.sol
  packages/core/contracts/financial-templates/expiring-multiparty/PricelessPositionManager.sol
  packages/core/contracts/oracle/implementation/OptimisticOracle.sol
  packages/core/contracts/oracle/implementation/test/OptimisticRequesterTest.sol
  packages/core/contracts/oracle/interfaces/OptimisticOracleInterface.sol
  packages/core/test/oracle/OptimisticOracle.js
Labels: dec-2020-audit

#2329 fix(dec-20-audit): [H01] Bond penalty may not apply
  packages/core/contracts/oracle/implementation/OptimisticOracle.sol
  packages/core/test/financial-templates/common/FundingRateApplier.js
  packages/core/test/oracle/OptimisticOracle.js
Labels: dec-2020-audit

#2345 improve(dec-20-audit): [N02] Consider ERC777 tokens
  packages/core/contracts/financial-templates/expiring-multiparty/Liquidatable.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLiquidatable.sol
Labels: dec-2020-audit

#2327 fix(dec-20-audit): [N07] TODOs in code
  packages/core/contracts/financial-templates/common/FeePayer.sol
  packages/core/contracts/financial-templates/expiring-multiparty/Liquidatable.sol
  packages/core/contracts/financial-templates/expiring-multiparty/PricelessPositionManager.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLiquidatable.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualPositionManager.sol
  packages/core/test/financial-templates/expiring-multiparty/PricelessPositionManager.js
  packages/core/test/financial-templates/perpetual-multiparty/PerpetualPositionManager.js
Labels: dec-2020-audit

#2332 improve(dec-20-audit): [N04] Naming issues hinder code understanding
  packages/affiliates/test/truffle/contracts.js
  packages/common/src/Enums.js
  packages/core/contracts/financial-templates/common/FundingRateApplier.sol
  packages/core/contracts/financial-templates/expiring-multiparty/ExpiringMultiPartyCreator.sol
  packages/core/contracts/financial-templates/expiring-multiparty/Liquidatable.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/ConfigStore.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/ConfigStoreInterface.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualCreator.sol
  packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLiquidatable.sol
  packages/core/scripts/DeploySyntheticTokens.js
  packages/core/scripts/IntegrationTests.js
  packages/core/scripts/PrecisionErrors.js
  packages/core/scripts/local/DeployEMP.js
  packages/core/scripts/umip-3/4_ExecuteSimulate.js
  packages/core/test/financial-templates/common/FundingRateApplier.js
  packages/core/test/financial-templates/expiring-multiparty/ExpiringMultiParty.js
  packages/core/test/financial-templates/expiring-multiparty/ExpiringMultiPartyCreator.js
  packages/core/test/financial-templates/expiring-multiparty/Liquidatable.js
  packages/core/test/financial-templates/perpetual-multiparty/ConfigStore.js
  packages/core/test/financial-templates/perpetual-multiparty/Perpetual.js
  packages/core/test/financial-templates/perpetual-multiparty/PerpetualCreator.js
  packages/core/test/financial-templates/perpetual-multiparty/PerpetualLiquidatable.js
  packages/core/test/financial-templates/perpetual-multiparty/PerpetualPositionManager.js
  packages/disputer/test/Disputer.js
  packages/disputer/test/index.js
  packages/financial-templates-lib/test/clients/ExpiringMultiPartyClient.js
  packages/financial-templates-lib/test/clients/ExpiringMultiPartyEventClient.js
  packages/financial-templates-lib/test/price-feed/CreatePriceFeed.js
  packages/liquidator/test/Liquidator.js
  packages/liquidator/test/index.js
  packages/monitors/test/CRMonitor.js
  packages/monitors/test/ContractMonitor.js
  packages/monitors/test/index.js
  packages/reporters/index.js
  yarn.lock
Labels: dec-2020-audit

#2347 improve(dec-20-audit): [N02] Consider ERC777 tokens (continued)
  packages/core/contracts/oracle/implementation/OptimisticOracle.sol
Labels: dec-2020-audit

#2344 improve(financial-templates-lib): Update @uma/core version to latest and fix tests and clients to correct versions
  packages/financial-templates-lib/package.json
  packages/financial-templates-lib/src/price-feed/CreatePriceFeed.js
  packages/financial-templates-lib/test/clients/ExpiringMultiPartyClient.js
  packages/financial-templates-lib/test/clients/ExpiringMultiPartyEventClient.js
  packages/financial-templates-lib/test/clients/TokenBalanceClient.js
  packages/financial-templates-lib/test/price-feed/BalancerPriceFeed.js
  packages/financial-templates-lib/test/price-feed/CreatePriceFeed.js
  packages/financial-templates-lib/test/truffle/UniswapPriceFeed.js
Labels: bots
