Repository UMAprotocol/protocol, pull requests merged in 2020-04, with the labels that each got.

#1150 Make definition of "expiry" for requested withdrawals consistent with rest of EMP
  core/contracts/financial-templates/implementation/PricelessPositionManager.sol
  core/scripts/PrecisionErrors.js
  core/scripts/cli/sponsor/withdraw.js
  core/scripts/local/AdvanceEMP.js
  core/scripts/local/DeployEMP.js
  core/test/financial-templates/PricelessPositionManager.js
Labels: bug

#1162 Resolve precision loss in functions that call `_removeCollateral()` and withdraw collateral to the caller
  core/contracts/financial-templates/implementation/FeePayer.sol
  core/contracts/financial-templates/implementation/Liquidatable.sol
  core/contracts/financial-templates/implementation/PricelessPositionManager.sol
  core/scripts/PrecisionErrors.js
  core/test/financial-templates/Liquidatable.js
  core/test/financial-templates/PricelessPositionManager.js
Labels: bug

#1178 Sponsor CLI: confirms withdrawal amount for redeem and withdraw before unwrapping WETH collateral
  core/scripts/cli/sponsor/redeem.js
  core/scripts/cli/sponsor/withdraw.js
  core/scripts/local/DeployEMP.js
Labels: bug

#1157 Change "price feed" in Liquidator bot into a "price function" to standardize with Disputer bot
  liquidator/index.js
  liquidator/liquidator.js
  liquidator/test/Liquidator.js
Labels: tech debt

#1179 EMP Client: add external methods update() and forceUpdate()
  financial-templates-lib/ExpiringMultiPartyClient.js
  financial-templates-lib/test/ExpiringMultiPartyClient.js
Labels: tech debt

#1180 Liquidator/Disputer bots update EMP client lazily
  disputer/disputer.js
  disputer/test/Disputer.js
  liquidator/liquidator.js
  liquidator/test/Liquidator.js
Labels: tech debt

#1191 [P1-H02] Add ability for Governor to execute payable proposed transactions
  core/contracts/oracle/implementation/Governor.sol
  core/test/oracle/Governor.js
Labels: audit-fix-phase1

#1201 [P1-N16] Mark contracts not meant to be instantiated as `abstract`
  core/contracts/common/implementation/MultiRole.sol
  core/contracts/common/implementation/Testable.sol
  core/contracts/common/implementation/Withdrawable.sol
  core/contracts/oracle/implementation/ContractCreator.sol
Labels: audit-fix-phase1

#1200 [P1-H03] Prevent re-entrancy on Governor executeProposal
  core/contracts/common/test/ReentrancyChecker.sol
  core/contracts/oracle/implementation/Governor.sol
  core/test/oracle/Governor.js
Labels: audit-fix-phase1

#1194 [P1-M04] Refactor registry to prevent multiple address registration during inital contract registration
  core/contracts/oracle/implementation/Registry.sol
  core/test/oracle/Registry.js
Labels: audit-fix-phase1

#1206 [P1-N04] Fix typos
  core/contracts/common/implementation/MultiRole.sol
  core/contracts/oracle/implementation/IdentifierWhitelist.sol
  core/contracts/oracle/implementation/Registry.sol
  core/contracts/oracle/implementation/ResultComputation.sol
  core/contracts/oracle/implementation/Voting.sol
  core/contracts/oracle/interfaces/IdentifierWhitelistInterface.sol
  core/contracts/oracle/interfaces/OracleInterface.sol
  core/contracts/oracle/interfaces/VotingInterface.sol
Labels: audit-fix-phase1

#1205 [P1-N05] Use SafeERC20 in Withdrawable and Store
  core/contracts/common/implementation/Withdrawable.sol
  core/contracts/oracle/implementation/Store.sol
Labels: audit-fix-phase1

#1207 [P1-L11] Correct element deletion in pendingPriceRequests array
  core/contracts/oracle/implementation/Voting.sol
  core/contracts/oracle/implementation/test/VotingTest.sol
  core/test/oracle/Voting.js
Labels: audit-fix-phase1

#1204 [P1-M02] Test and document the bytes32 manipulation functions in Governor.sol
  core/contracts/oracle/implementation/Governor.sol
  core/contracts/oracle/implementation/test/GovernorTest.sol
  core/test/oracle/Governor.js
Labels: audit-fix-phase1

#1210 [P1-L02] Prevent EOAs from registering in the finder
  core/contracts/oracle/implementation/Finder.sol
  core/test/oracle/Finder.js
Labels: audit-fix-phase1

#1214 [P1-L14] Add events to store state fee update
  core/contracts/oracle/implementation/Store.sol
  core/test/oracle/Store.js
Labels: audit-fix-phase1

#1228 [P1-N11] Remove hard-coded condition statement in require
  core/contracts/common/implementation/MultiRole.sol
Labels: audit-fix-phase1

#1226 [P1-L13] Add onlyValidRole to setWithdrawRole
  core/contracts/common/implementation/Withdrawable.sol
  core/contracts/common/test/WithdrawableTest.sol
  core/test/common/Withdrawable.js
Labels: audit-fix-phase1

#1225 [P1-L10] Replace transfer with sendValue
  core/contracts/common/implementation/Withdrawable.sol
Labels: audit-fix-phase1

#1213 [P1-L12] Address a number of erroneous comments through the DVM
  core/contracts/oracle/implementation/DesignatedVoting.sol
  core/contracts/oracle/implementation/Governor.sol
  core/contracts/oracle/implementation/Registry.sol
  core/contracts/oracle/implementation/ResultComputation.sol
  core/contracts/oracle/implementation/Voting.sol
Labels: audit-fix-phase1

#1235 [P1-L16] Use SafeMath to add uints for rewards expiration time
  core/contracts/oracle/implementation/Voting.sol
  core/test/oracle/Voting.js
Labels: audit-fix-phase1

#1217 [P1-H01] Require additional data in vote commit hash to prevent duplication of votes
  common/EncryptionHelper.js
  common/VotingUtils.js
  core/contracts/oracle/implementation/Voting.sol
  core/scripts/local/BatchGasEstimation.js
  core/scripts/local/VoteGasEstimation.js
  core/test/oracle/DesignatedVoting.js
  core/test/oracle/Governor.js
  core/test/oracle/Voting.js
  voter-dapp/src/ActiveRequests.js
Labels: audit-fix-phase1

#1230 [P1-N03] Replace all uint with uint256
  core/contracts/Migrations.sol
  core/contracts/common/implementation/AddressWhitelist.sol
  core/contracts/common/implementation/ExpandedERC20.sol
  core/contracts/common/implementation/FixedPoint.sol
  core/contracts/common/implementation/MultiRole.sol
  core/contracts/common/implementation/Testable.sol
  core/contracts/common/implementation/TestnetERC20.sol
  core/contracts/common/implementation/Withdrawable.sol
  core/contracts/common/interfaces/ExpandedIERC20.sol
  core/contracts/common/test/FixedPointTest.sol
  core/contracts/common/test/MultiRoleTest.sol
  core/contracts/common/test/TestableTest.sol
  core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol
  core/contracts/financial-templates/implementation/FeePayer.sol
  core/contracts/financial-templates/implementation/Liquidatable.sol
  core/contracts/financial-templates/implementation/PricelessPositionManager.sol
  core/contracts/financial-templates/implementation/WETH9.sol
  core/contracts/oracle/implementation/DesignatedVoting.sol
  core/contracts/oracle/implementation/Governor.sol
  core/contracts/oracle/implementation/Registry.sol
  core/contracts/oracle/implementation/ResultComputation.sol
  core/contracts/oracle/implementation/Store.sol
  core/contracts/oracle/implementation/TokenMigrator.sol
  core/contracts/oracle/implementation/VoteTiming.sol
  core/contracts/oracle/implementation/Voting.sol
  core/contracts/oracle/implementation/test/GovernorTest.sol
  core/contracts/oracle/implementation/test/MockAdministratee.sol
  core/contracts/oracle/implementation/test/ResultComputationTest.sol
  core/contracts/oracle/implementation/test/VoteTimingTest.sol
  core/contracts/oracle/implementation/test/VotingTest.sol
  core/contracts/oracle/interfaces/OracleInterface.sol
  core/contracts/oracle/interfaces/StoreInterface.sol
  core/contracts/oracle/interfaces/VotingInterface.sol
  core/contracts/oracle/test/MockOracle.sol
  core/contracts/tokenized-derivative/LeveragedReturnCalculator.sol
  core/contracts/tokenized-derivative/ManualPriceFeed.sol
  core/contracts/tokenized-derivative/PriceFeedInterface.sol
  core/contracts/tokenized-derivative/ReturnCalculatorInterface.sol
  core/contracts/tokenized-derivative/TokenizedDerivative.sol
  core/contracts/tokenized-derivative/TokenizedDerivativeCreator.sol
Labels: audit-fix-phase1

#1240 [P1-L09] Suppress reward events if user already retrieved or didn't vote
  core/contracts/oracle/implementation/Voting.sol
  core/test/oracle/Voting.js
Labels: audit-fix-phase1

#1212 [P1-L08] Add input validation throughout DVM
  core/contracts/common/implementation/MultiRole.sol
  core/contracts/oracle/implementation/Store.sol
  core/contracts/oracle/implementation/VoteTiming.sol
  core/test/common/MultiRole.js
  core/test/oracle/Store.js
  core/test/oracle/VoteTiming.js
Labels: audit-fix-phase1

#1236 [P1-N08] Converge upon single source of time for all contracts in testing environments
  core/contracts/common/implementation/Testable.sol
  core/contracts/common/implementation/Timer.sol
  core/contracts/common/test/TestableTest.sol
  core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol
  core/contracts/financial-templates/implementation/FeePayer.sol
  core/contracts/financial-templates/implementation/Liquidatable.sol
  core/contracts/financial-templates/implementation/PricelessPositionManager.sol
  core/contracts/oracle/implementation/Governor.sol
  core/contracts/oracle/implementation/Voting.sol
  core/contracts/oracle/implementation/test/GovernorTest.sol
  core/contracts/oracle/implementation/test/VotingTest.sol
  core/contracts/oracle/test/MockOracle.sol
  core/contracts/tokenized-derivative/ManualPriceFeed.sol
  core/contracts/tokenized-derivative/TokenizedDerivativeCreator.sol
  core/migrations/10_deploy_designated_voting_factory.js
  core/migrations/11_deploy_price_feed.js
  core/migrations/11_support_identifiers.js
  core/migrations/12_deploy_price_feed.js
  core/migrations/13_deploy_tokenized_derivative_utils.js
  core/migrations/14_deploy_tokenized_derivative_creator.js
  core/migrations/15_deploy_register_creator.js
  core/migrations/16_deploy_testnet_token.js
  core/migrations/17_deploy_return_calculators.js
  core/migrations/18_deploy_tokenfactory.js
  core/migrations/19_deploy_expiring_multi_party_creator.js
  core/migrations/20_deploy_local_weth.js
  core/migrations/3_deploy_timer.js
  core/migrations/4_deploy_voting_token.js
  core/migrations/5_deploy_voting.js
  core/migrations/6_deploy_registry.js
  core/migrations/7_deploy_financial_contracts_admin.js
  core/migrations/8_deploy_store.js
  core/migrations/9_deploy_governor.js
  core/scripts/IntegrationTests.js
  core/scripts/PrecisionErrors.js
  core/scripts/cli/sponsor/marketUtils.js
  core/scripts/local/AdvanceEMP.js
  core/scripts/local/DeployEMP.js
  core/scripts/local/InitializeSystem.js
  core/test/common/Testable.js
  core/test/financial-templates/ExpiringMultiParty.js
  core/test/financial-templates/ExpiringMultiPartyCreator.js
  core/test/financial-templates/Liquidatable.js
  core/test/financial-templates/PricelessPositionManager.js
  core/test/oracle/Governor.js
  core/test/oracle/Voting.js
  core/test/tokenized-derivative/ManualPriceFeed.js
  core/test/tokenized-derivative/TokenizedDerivative.js
  disputer/test/Disputer.js
  disputer/test/index.js
  financial-templates-lib/test/ExpiringMultiPartyClient.js
  financial-templates-lib/test/ExpiringMultiPartyEventClient.js
  financial-templates-lib/test/GasEstimator.js
  liquidator/test/Liquidator.js
  liquidator/test/index.js
Labels: audit-fix-phase1

#1237 [P1-L01] Compute late penalty based on current time rather than endTime
  core/contracts/oracle/implementation/Store.sol
  core/migrations/8_deploy_store.js
  core/test/financial-templates/Liquidatable.js
  core/test/financial-templates/PricelessPositionManager.js
  core/test/oracle/Store.js
  core/test/tokenized-derivative/TokenizedDerivative.js
Labels: audit-fix-phase1

#1231 [P1-N15] Remove EncryptedStore and emit an extra event instead
  common/VotingUtils.js
  core/contracts/oracle/implementation/EncryptedStore.sol
  core/contracts/oracle/implementation/Voting.sol
  core/scripts/Voting.js
  core/test/oracle/DesignatedVoting.js
  core/test/oracle/EncryptedStore.js
  core/test/oracle/Voting.js
  core/test/scripts/Voting.js
Labels: audit-fix-phase1

#1241 [P1-L05] Centralized defined interface storage library
  core/contracts/financial-templates/implementation/FeePayer.sol
  core/contracts/financial-templates/implementation/PricelessPositionManager.sol
  core/contracts/oracle/implementation/Constants.sol
  core/contracts/oracle/implementation/DesignatedVoting.sol
  core/contracts/oracle/implementation/Governor.sol
  core/contracts/oracle/implementation/Voting.sol
  core/contracts/tokenized-derivative/TokenizedDerivative.sol
  core/scripts/IntegrationTests.js
  core/scripts/PrecisionErrors.js
  core/scripts/local/DeployEMP.js
  core/test/financial-templates/Liquidatable.js
  core/test/financial-templates/PricelessPositionManager.js
  core/test/tokenized-derivative/TokenizedDerivative.js
  disputer/test/Disputer.js
  financial-templates-lib/test/ExpiringMultiPartyClient.js
  financial-templates-lib/test/ExpiringMultiPartyEventClient.js
  liquidator/test/Liquidator.js
Labels: audit-fix-phase1

#1242 [P1-L15] Prevent Governor proposals with data from being sent to EOA accounts
  core/contracts/oracle/implementation/Governor.sol
  core/test/oracle/Governor.js
Labels: audit-fix-phase1

#1238 [P1-M01] Separate round snapshot function
  core/contracts/oracle/implementation/Voting.sol
  core/contracts/oracle/interfaces/VotingInterface.sol
  core/test/oracle/Voting.js
Labels: audit-fix-phase1

#1250 [P1-N02] Remove TODOs
  core/contracts/common/implementation/FixedPoint.sol
  core/contracts/oracle/implementation/ContractCreator.sol
  core/contracts/oracle/implementation/ResultComputation.sol
Labels: audit-fix-phase1

#1246 Only reference IdentifierWhitelist from Finder
  core/contracts/oracle/implementation/Voting.sol
  core/contracts/oracle/implementation/test/VotingTest.sol
  core/contracts/oracle/test/MockOracle.sol
  core/migrations/5_deploy_voting.js
  core/scripts/IntegrationTests.js
  core/scripts/PrecisionErrors.js
  core/scripts/local/DeployEMP.js
  core/test/financial-templates/Liquidatable.js
  core/test/financial-templates/PricelessPositionManager.js
  core/test/oracle/Voting.js
  core/test/tokenized-derivative/TokenizedDerivative.js
  disputer/test/Disputer.js
  financial-templates-lib/test/ExpiringMultiPartyClient.js
  financial-templates-lib/test/ExpiringMultiPartyEventClient.js
  liquidator/test/Liquidator.js
Labels: tech debt

#1251 [P1-N14] Test and document late fee behavior
  core/contracts/oracle/implementation/Store.sol
  core/test/oracle/Store.js
Labels: audit-fix-phase1

#1227 [P1-N07] Contract naming updates
  core/contracts/common/implementation/FixedPoint.sol
  core/contracts/common/implementation/Withdrawable.sol
  core/contracts/oracle/implementation/Store.sol
  core/scripts/IntegrationTests.js
  core/scripts/PrecisionErrors.js
  core/test/financial-templates/Liquidatable.js
  core/test/financial-templates/PricelessPositionManager.js
  core/test/oracle/Store.js
  core/test/tokenized-derivative/TokenizedDerivative.js
Labels: audit-fix-phase1

#1229 [P1-N09] Only return named variables
  core/contracts/oracle/implementation/DesignatedVoting.sol
  core/contracts/oracle/implementation/DesignatedVotingFactory.sol
  core/contracts/oracle/implementation/Finder.sol
  core/contracts/oracle/implementation/Governor.sol
  core/contracts/oracle/implementation/Store.sol
  core/contracts/oracle/implementation/VoteTiming.sol
  core/contracts/oracle/implementation/Voting.sol
  core/contracts/oracle/implementation/test/GovernorTest.sol
  core/contracts/oracle/interfaces/FinderInterface.sol
  core/contracts/oracle/interfaces/StoreInterface.sol
  core/contracts/oracle/test/MockOracle.sol
Labels: audit-fix-phase1

#1255 [P1-L19] Explicitly pass in amount of ERC20 to pay as fees
  core/contracts/financial-templates/implementation/FeePayer.sol
  core/contracts/oracle/implementation/Store.sol
  core/contracts/oracle/interfaces/StoreInterface.sol
  core/contracts/tokenized-derivative/TokenizedDerivative.sol
  core/test/oracle/Store.js
Labels: audit-fix-phase1

#1247 [P1-L03] MultiRole roles can be renounced
  core/contracts/common/implementation/MultiRole.sol
  core/test/common/MultiRole.js
Labels: audit-fix-phase1

#1254 [P1-L18] Pin @openzeppelin dependency to fixed version: v3.0.0-rc.1
  core/contracts/common/implementation/AddressWhitelist.sol
  core/contracts/common/implementation/ExpandedERC20.sol
  core/contracts/common/implementation/TestnetERC20.sol
  core/contracts/financial-templates/implementation/SyntheticToken.sol
  core/contracts/oracle/implementation/FinancialContractsAdmin.sol
  core/contracts/oracle/implementation/Finder.sol
  core/contracts/oracle/implementation/IdentifierWhitelist.sol
  core/contracts/oracle/implementation/TokenMigrator.sol
  core/contracts/oracle/implementation/Voting.sol
  core/contracts/oracle/implementation/VotingToken.sol
  core/contracts/tokenized-derivative/LeveragedReturnCalculator.sol
  core/contracts/tokenized-derivative/ManualPriceFeed.sol
  core/contracts/tokenized-derivative/TokenizedDerivative.sol
  core/scripts/IntegrationTests.js
  core/scripts/PrecisionErrors.js
  core/scripts/local/CreateMarginToken.js
  core/scripts/local/InitializeSystem.js
  core/test/common/Withdrawable.js
  core/test/financial-templates/ExpiringMultiParty.js
  core/test/financial-templates/ExpiringMultiPartyCreator.js
  core/test/financial-templates/Liquidatable.js
  core/test/financial-templates/PricelessPositionManager.js
  core/test/oracle/Store.js
  core/test/tokenized-derivative/TokenizedDerivative.js
  disputer/test/Disputer.js
  disputer/test/index.js
  financial-templates-lib/test/ExpiringMultiPartyClient.js
  financial-templates-lib/test/ExpiringMultiPartyEventClient.js
  liquidator/test/Liquidator.js
  liquidator/test/index.js
  package.json
Labels: audit-fix-phase1

#1259 [P1-L04] Update require messages
  core/contracts/oracle/implementation/Finder.sol
  core/contracts/oracle/implementation/Governor.sol
  core/contracts/oracle/implementation/Registry.sol
  core/contracts/oracle/implementation/Store.sol
  core/contracts/oracle/implementation/TokenMigrator.sol
  core/contracts/oracle/implementation/Voting.sol
  package.json
Labels: audit-fix-phase1

#1256 [P1-L22] initialize fee percentages in Store constructor
  core/contracts/oracle/implementation/Store.sol
  core/migrations/8_deploy_store.js
  core/test/oracle/Store.js
Labels: audit-fix-phase1

#1270 [P1-N12] Add NatSpec comments to remaining external DVM methods
  core/contracts/common/implementation/AddressWhitelist.sol
  core/contracts/common/implementation/ExpandedERC20.sol
  core/contracts/common/implementation/FixedPoint.sol
  core/contracts/common/implementation/MultiRole.sol
  core/contracts/common/implementation/TestnetERC20.sol
  core/contracts/common/implementation/Timer.sol
  core/contracts/common/implementation/Withdrawable.sol
  core/contracts/oracle/implementation/DesignatedVoting.sol
  core/contracts/oracle/implementation/VoteTiming.sol
  core/contracts/oracle/implementation/Voting.sol
  core/contracts/oracle/interfaces/StoreInterface.sol
Labels: audit-fix-phase1

#1272 [P1-N01] Add clarifying comment about initial round ID not starting at 0 or 1
  core/contracts/oracle/implementation/VoteTiming.sol
Labels: audit-fix-phase1

#1273 [P1-N10] Warn users against re-using salts
  core/contracts/oracle/implementation/Voting.sol
  core/contracts/oracle/interfaces/VotingInterface.sol
  documentation/oracle/dvm_interfaces.md
Labels: audit-fix-phase1

#1271 [P1-N06] Small formatting corrections to DVM
  core/contracts/common/implementation/ExpandedERC20.sol
  core/contracts/common/implementation/Testable.sol
  core/contracts/common/implementation/TestnetERC20.sol
  core/contracts/common/implementation/Timer.sol
  core/contracts/common/implementation/Withdrawable.sol
  core/contracts/common/test/WithdrawableTest.sol
  core/contracts/oracle/implementation/DesignatedVoting.sol
  core/contracts/oracle/implementation/DesignatedVotingFactory.sol
  core/contracts/oracle/implementation/Governor.sol
  core/contracts/oracle/implementation/Registry.sol
  core/contracts/oracle/implementation/Store.sol
  core/contracts/oracle/implementation/Voting.sol
  core/contracts/tokenized-derivative/LeveragedReturnCalculator.sol
  core/contracts/tokenized-derivative/ManualPriceFeed.sol
Labels: audit-fix-phase1

#1299 [P1-N15] removed import
  core/contracts/financial-templates/implementation/ExpiringMultiParty.sol
Labels: audit-fix-phase2

#1304 [P02-L04] Fix unsafe addition of current time and withdrawal liveness
  core/contracts/financial-templates/implementation/PricelessPositionManager.sol
  core/test/financial-templates/PricelessPositionManager.js
Labels: audit-fix-phase2

#1296 DVM clients should filter on "roundId" instead of "resolutionRoundId"
  core/scripts/cli/voting/getResolvedVotesByRoundId.js
  voter-dapp/src/ResolvedRequests.js
  voter-dapp/src/RetrieveRewards.js
Labels: bug

#1303 [P2-N08] Removed unused repeated function in EMP
  core/contracts/financial-templates/implementation/PricelessPositionManager.sol
Labels: audit-fix-phase2

#1307 [P2-L01] Enforce Check-Effects-Interactions pattern in withdrawPassedRequest
  core/contracts/financial-templates/implementation/PricelessPositionManager.sol
Labels: audit-fix-phase2

#1298 [P2-N14] Fixed contract typos NFCT
  core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol
  core/contracts/financial-templates/implementation/FeePayer.sol
  core/contracts/financial-templates/implementation/Liquidatable.sol
  core/contracts/financial-templates/implementation/PricelessPositionManager.sol
  core/contracts/financial-templates/implementation/SyntheticToken.sol
  core/contracts/financial-templates/implementation/TokenFactory.sol
  core/test/financial-templates/Liquidatable.js
  financial-templates-lib/ExpiringMultiPartyEventClient.js
Labels: audit-fix-phase2

#1308 [P02-N02] Store valid timestamps in a map rather than an array
  core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol
  core/test/financial-templates/ExpiringMultiPartyCreator.js
Labels: audit-fix-phase2

#1315 [P02-N07] Add view modifier to function that doesn't modify storage
  core/contracts/financial-templates/implementation/FeePayer.sol
Labels: audit-fix-phase2

#1126 Add Slither back to CI
  .circleci/config.yml
  ci/install_node_npm.sh
  ci/run_slither.sh
  core/contracts/common/test/WithdrawableTest.sol
  core/contracts/financial-templates/implementation/FeePayer.sol
  core/contracts/financial-templates/implementation/Liquidatable.sol
Labels: tech debt

#1317 [P02-N06] Index parameters in events
  core/contracts/financial-templates/implementation/ExpiringMultiPartyCreator.sol
  core/contracts/financial-templates/implementation/Liquidatable.sol
Labels: audit-fix-phase2

#1320 Remove hardcoded "registry" string in ContractCreator
  core/contracts/oracle/implementation/ContractCreator.sol
Labels: tech debt

#1325 Added link to docs for 2 key contract in voter Dapp
  voter-dapp/src/DesignatedVotingDeployment.js
Labels: enhancement

#1316 [P2-L02] Additional input validation
  core/contracts/financial-templates/implementation/FeePayer.sol
  core/contracts/financial-templates/implementation/PricelessPositionManager.sol
  core/test/financial-templates/ExpiringMultiParty.js
  core/test/financial-templates/Liquidatable.js
  core/test/financial-templates/PricelessPositionManager.js
Labels: audit-fix-phase2

#1314 [P2-M01] Subject transfers of sponsor positions to liveness period
  core/contracts/financial-templates/implementation/PricelessPositionManager.sol
  core/test/financial-templates/PricelessPositionManager.js
Labels: audit-fix-phase2

#1327 [P02-N13] Remove TODOs
  core/contracts/financial-templates/implementation/Liquidatable.sol
  core/contracts/financial-templates/implementation/PricelessPositionManager.sol
Labels: audit-fix-phase2

#1326 Token balance monitor client
  financial-templates-lib/TokenBalanceClient.js
  financial-templates-lib/test/TokenBalanceClient.js
Labels: enhancement

#1339 [P02-N03] Use local variable instead of calling helper function twice
  core/contracts/financial-templates/implementation/FeePayer.sol
Labels: audit-fix-phase2

#1341 [P02-N12] Adjust naming of variables and functions
  core/contracts/financial-templates/implementation/FeePayer.sol
  core/contracts/financial-templates/implementation/Liquidatable.sol
  core/contracts/financial-templates/implementation/PricelessPositionManager.sol
  core/test/financial-templates/ExpiringMultiPartyCreator.js
  core/test/financial-templates/Liquidatable.js
  core/test/financial-templates/PricelessPositionManager.js
Labels: audit-fix-phase2

#1343 [P01-N11] Add documentation for a few internal methods
  core/contracts/financial-templates/implementation/PricelessPositionManager.sol
Labels: audit-fix-phase2
