Repository UMAprotocol/protocol, pull requests merged in 2021-11, with the labels that each got.

#3526 fix(lsp): Fix request early expiration with timestamp of 0
  packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol
  packages/core/test/financial-templates/long-short-pair/LongShortPair.js
Labels: audit-fix-phase5

#3535 fix(BridgePool): add more indexed params
  packages/core/contracts/insured-bridge/BridgeDepositBox.sol
  packages/core/contracts/insured-bridge/avm/AVM_BridgeDepositBox.sol
  packages/core/contracts/insured-bridge/interfaces/BridgeAdminInterface.sol
  packages/core/contracts/insured-bridge/ovm/OVM_BridgeDepositBox.sol
Labels: audit-fix-phase5

#3537 fix(BridgeAdmin): validated amount sent is correct when making admin calls
  packages/core/contracts/insured-bridge/BridgeAdmin.sol
Labels: audit-fix-phase5

#3533 fix(BridgePool): address missing nat-spec
  packages/core/contracts/insured-bridge/BridgeDepositBox.sol
  packages/core/contracts/insured-bridge/BridgePool.sol
  packages/core/contracts/insured-bridge/avm/AVM_BridgeDepositBox.sol
  packages/core/contracts/insured-bridge/ovm/OVM_BridgeDepositBox.sol
Labels: audit-fix-phase5

#3530 fix(BridgePool): remove redundant ExpandedERC20 import
  packages/core/contracts/insured-bridge/BridgePool.sol
Labels: audit-fix-phase5

#3529 fix(lsp): Fix requestEarlyExpiration and expire natspec comments
  packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol
Labels: audit-fix-phase5

#3528 fix(lsp): Fix inconsistent type casting for expiration timestamp
  packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol
Labels: audit-fix-phase5

#3527 fix(lsp): Fix incorrect inequality for expiration timestamp in settle method
  packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol
Labels: audit-fix-phase5

#3523 fix(lsp): remove duplicate transfer in factory
  packages/core/contracts/financial-templates/long-short-pair/LongShortPairCreator.sol
  packages/core/test/financial-templates/long-short-pair/LongShortPairCreator.js
Labels: audit-fix-phase5

#3540 fix(BridgeAdmin): Fix typographical in contracts
  packages/common/src/Constants.ts
  packages/core/CHANGELOG.md
  packages/core/contracts/common/implementation/FixedPoint.sol
  packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol
  packages/core/contracts/financial-templates/long-short-pair/LongShortPairCreator.sol
  packages/core/contracts/insured-bridge/BridgeDepositBox.sol
  packages/core/contracts/insured-bridge/BridgePool.sol
  packages/core/contracts/insured-bridge/avm/AVM_BridgeDepositBox.sol
  packages/core/contracts/insured-bridge/ovm/OVM_BridgeDepositBox.sol
  packages/core/contracts/insured-bridge/test/BridgeDepositBoxMock.sol
  packages/core/test/financial-templates/long-short-pair/LongShortPair.js
  packages/insured-bridge-relayer/test/Relayer.ts
Labels: audit-fix-phase5

#3531 fix(skinny-optimistic-oracle): proposePrice callback should be to requester not msg.sender
  packages/core/contracts/oracle/implementation/SkinnyOptimisticOracle.sol
Labels: audit-fix-phase5

#3532 fix(ancillary-data-lib): Fix faulty append function
  packages/core/contracts/common/implementation/AncillaryData.sol
  packages/core/contracts/common/test/AncillaryDataTest.sol
  packages/core/test/common/AncillaryData.js
Labels: audit-fix-phase5

#3534 fix(skinny-optimistic-oracle): Default proposer bond to final fee in requestAndProposePriceFor
  packages/core/contracts/oracle/implementation/SkinnyOptimisticOracle.sol
  packages/core/test/oracle/SkinnyOptimisticOracle.js
Labels: audit-fix-phase5

#3538 improve(insured-bridge): Reduce verbosity of _getDepositHash()
  packages/core/contracts/insured-bridge/BridgePool.sol
  packages/core/test/insured-bridge/BridgePool.js
  packages/financial-templates-lib/src/clients/InsuredBridgeL2Client.ts
  packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
  packages/financial-templates-lib/test/clients/InsuredBridgeL2Client.js
Labels: audit-fix-phase5

#3539 fix(skinny-optimistic-oracle): Reentrancy guard requestAndProposePriceFor
  packages/core/contracts/oracle/implementation/SkinnyOptimisticOracle.sol
Labels: audit-fix-phase5

#3542 fix(insured-bridge): Remove unused modifier
  packages/core/contracts/insured-bridge/BridgePool.sol
Labels: audit-fix-phase5

#3524 fix(lsp): fix ancillary data length check in constructor for early expiration
  packages/core/contracts/financial-templates/long-short-pair/LongShortPair.sol
  packages/core/test/financial-templates/long-short-pair/LongShortPair.js
Labels: audit-fix-phase5

#3541 improve(arbitrum-messenger): Emit event including return value of Arbitrum sys contract call
  packages/core/contracts/insured-bridge/avm/Arbitrum_Messenger.sol
  packages/core/contracts/insured-bridge/test/Arbitrum_InboxMock.sol
  packages/core/test/insured-bridge/ArbitrumMessenger.js
Labels: audit-fix-phase5

#3536 improve(insured-bridge): Add require messages
  packages/core/contracts/insured-bridge/BridgePool.sol
Labels: audit-fix-phase5

#3516 improve(insured-bridge): BridgePool requires relay.quoteTime >= contract deployment time
  packages/core/contracts/insured-bridge/BridgePool.sol
  packages/core/test/insured-bridge/BridgePool.js
  packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
  packages/insured-bridge-relayer/src/Relayer.ts
  packages/insured-bridge-relayer/test/Relayer.ts
Labels: insured-bridge

#3551 improve(insured-bridge): Remove deploymentTime
  packages/core/contracts/insured-bridge/BridgePool.sol
  packages/core/test/insured-bridge/BridgePool.js
  packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
  packages/insured-bridge-relayer/test/Relayer.ts
Labels: insured-bridge

#3553 feat(insured-bridge): add back safe multicaller
  packages/core/contracts/common/implementation/MultiCaller.sol
  packages/core/contracts/insured-bridge/BridgePool.sol
Labels: insured-bridge

#3547 improve(insured-bridge): Reduce verbosity of _getDepositHash()
  packages/core/contracts/insured-bridge/BridgePool.sol
  packages/core/test/insured-bridge/BridgePool.js
  packages/financial-templates-lib/src/clients/InsuredBridgeL2Client.ts
  packages/financial-templates-lib/test/clients/InsuredBridgeL1Client.js
  packages/financial-templates-lib/test/clients/InsuredBridgeL2Client.js
Labels: insured-bridge

#3482 improve(insured-bridge): Adjustments for OVM 2.0 changes
  packages/common/src/HardhatConfig.ts
  packages/core/contracts/external/ovm/OVM_CrossDomainEnabled.sol
  packages/core/contracts/insured-bridge/ovm/OVM_BridgeDepositBox.sol
  packages/core/contracts/insured-bridge/ovm/OVM_CrossDomainEnabled.sol
  packages/core/contracts/insured-bridge/ovm/Optimism_Messenger.sol
  packages/core/contracts/insured-bridge/ovm/iOVM_CrossDomainMessenger.sol
  packages/core/contracts/insured-bridge/test/OVM_L1CrossDomainMessengerMock.sol
Labels: insured-bridge

#3586 feat(cross-chain-oracle): Generalized cross-chain oracle and governance contracts
  packages/core/contracts/cross-chain-oracle/ChildMessengerInterface.sol
  packages/core/contracts/cross-chain-oracle/GovernorHub.sol
  packages/core/contracts/cross-chain-oracle/GovernorSpoke.sol
  packages/core/contracts/cross-chain-oracle/OracleBase.sol
  packages/core/contracts/cross-chain-oracle/OracleHub.sol
  packages/core/contracts/cross-chain-oracle/OracleSpoke.sol
  packages/core/contracts/cross-chain-oracle/ParentMessengerInterface.sol
  packages/core/contracts/cross-chain-oracle/test/OracleBaseMock.sol
  packages/core/contracts/oracle/implementation/Constants.sol
  packages/core/test/cross-chain-oracle/GovernorSpoke.js
  packages/core/test/cross-chain-oracle/OracleBase.js
Labels: cross-chain-oracle

#3596 feat(cross-chain-oracle): Add unit tests
  packages/core/contracts/cross-chain-oracle/OracleHub.sol
  packages/core/contracts/cross-chain-oracle/OracleSpoke.sol
  packages/core/contracts/cross-chain-oracle/test/GovernorMessengerMock.sol
  packages/core/contracts/cross-chain-oracle/test/OracleMessengerMock.sol
  packages/core/test/cross-chain-oracle/GovernorHub.js
  packages/core/test/cross-chain-oracle/GovernorSpoke.js
  packages/core/test/cross-chain-oracle/OracleBase.js
  packages/core/test/cross-chain-oracle/OracleHub.js
  packages/core/test/cross-chain-oracle/OracleSpoke.js
Labels: cross-chain-oracle

#3620 feat(cross-chain-oracle): Add Polygon adapters
  packages/core/contracts/cross-chain-oracle/chain-adapters/Optimism_ChildMessenger.sol
  packages/core/contracts/cross-chain-oracle/chain-adapters/Optimism_ParentMessenger.sol
  packages/core/contracts/cross-chain-oracle/chain-adapters/Polygon_ChildMessenger.sol
  packages/core/contracts/cross-chain-oracle/chain-adapters/Polygon_ParentMessenger.sol
  packages/core/contracts/cross-chain-oracle/chain-adapters/test/Polygon_ChildMessengerMock.sol
  packages/core/contracts/cross-chain-oracle/chain-adapters/test/Polygon_ParentMessengerMock.sol
  packages/core/contracts/cross-chain-oracle/interfaces/ChildMessengerInterface.sol
  packages/core/contracts/cross-chain-oracle/interfaces/ParentMessengerInterface.sol
  packages/core/networks/5.json
  packages/core/networks/80001.json
  packages/core/test/cross-chain-oracle/chain-adapters/Optimism_ChildMessenger.js
  packages/core/test/cross-chain-oracle/chain-adapters/Optimism_ParentMessenger.js
  packages/core/test/cross-chain-oracle/chain-adapters/Polygon_ChildMessenger.js
  packages/core/test/cross-chain-oracle/chain-adapters/Polygon_ParentMessenger.js
Labels: cross-chain-oracle

#3617 fix(cross-chain-oracle): add additional cross-chain admin logic
  packages/core/contracts/cross-chain-oracle/chain-adapters/Optimism_ParentMessenger.sol
Labels: cross-chain-oracle

#3622 feat(across): Add Setter for LP Fee %/second in BridgePool
  packages/core/contracts/insured-bridge/BridgeAdmin.sol
  packages/core/contracts/insured-bridge/BridgePool.sol
  packages/core/contracts/insured-bridge/interfaces/BridgeAdminInterface.sol
  packages/core/contracts/insured-bridge/interfaces/BridgePoolInterface.sol
  packages/core/test/insured-bridge/BridgeAdmin.js
  packages/core/test/insured-bridge/BridgePool.js
Labels: insured-bridge

#3626 improve(cross-chain-oracle): Allow publishPrice to be called for any DVM resolved price
  packages/core/contracts/cross-chain-oracle/OracleBase.sol
  packages/core/contracts/cross-chain-oracle/OracleHub.sol
  packages/core/test/cross-chain-oracle/OracleBase.js
  packages/core/test/cross-chain-oracle/OracleSpoke.js
Labels: cross-chain-oracle

#3624 fix(across): address possible underflow in bridge pool
  packages/core/contracts/insured-bridge/BridgePool.sol
  packages/core/test/insured-bridge/BridgePool.js
Labels: insured-bridge

#3627 improve(cross-chain-oracle): Change OracleSpoke stamped ancillary data contents
  packages/core/contracts/cross-chain-oracle/OracleHub.sol
  packages/core/contracts/cross-chain-oracle/OracleSpoke.sol
  packages/core/contracts/cross-chain-oracle/chain-adapters/Optimism_ParentMessenger.sol
  packages/core/test/cross-chain-oracle/OracleSpoke.js
  packages/core/test/cross-chain-oracle/chain-adapters/Optimism_ChildMessenger.js
Labels: cross-chain-oracle

#3629 feat(across): bridge admin to enable/disable pool relays
  packages/core/contracts/insured-bridge/BridgeAdmin.sol
  packages/core/contracts/insured-bridge/BridgePool.sol
  packages/core/contracts/insured-bridge/interfaces/BridgePoolInterface.sol
  packages/core/test/insured-bridge/ArbitrumMessenger.js
  packages/core/test/insured-bridge/BridgeAdmin.js
  packages/core/test/insured-bridge/BridgePool.js
  packages/core/test/insured-bridge/OptimismMessenger.js
Labels: insured-bridge

#3634 feat(cross-chain-oracle): Add multicaller to oracleHub and spoke
  packages/core/contracts/cross-chain-oracle/GovernorHub.sol
  packages/core/contracts/cross-chain-oracle/OracleHub.sol
Labels: cross-chain-oracle

#3631 feat: add Admin_ChildMessenger
  packages/core/contracts/cross-chain-oracle/chain-adapters/Admin_ChildMessenger.sol
  packages/core/contracts/cross-chain-oracle/chain-adapters/Arbitrum_ChildMessenger.sol
  packages/core/contracts/cross-chain-oracle/chain-adapters/Optimism_ChildMessenger.sol
  packages/core/contracts/cross-chain-oracle/chain-adapters/Polygon_ChildMessenger.sol
  packages/core/test/cross-chain-oracle/chain-adapters/Admin_ChildMessenger.js
Labels: cross-chain-oracle
